version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: vibration_api
    ports:
      - "8010:8000"
    env_file:
      - .env
    environment:
      - RUN_ENV=api
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: vibration_worker
    env_file:
      - .env
    environment:
      - RUN_ENV=worker
    depends_on:
      - db


  db:
    image: postgis/postgis:15-3.3
    container_name: vibration_db
    environment:
      POSTGRES_USER: hydrian_user
      POSTGRES_PASSWORD: hydrian_pass
      POSTGRES_DB: hydrian_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
